"""add_silver_tables

Revision ID: 454eda74d1b4
Revises: cc83a31393a7
Create Date: 2026-06-23 09:17:58.910323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '454eda74d1b4'
down_revision: Union[str, Sequence[str], None] = 'cc83a31393a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('silver_incident',
    sa.Column('silver_incident_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ingestion_batch_id', sa.UUID(), nullable=True),
    sa.Column('incident_code', sa.String(), nullable=True),
    sa.Column('machine_id', sa.String(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('severity', sa.SmallInteger(), nullable=True),
    sa.Column('shift', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('is_label_event', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['ingestion_batch_id'], ['ingestion_batch.ingestion_batch_id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['operator.operator_id'], ),
    sa.PrimaryKeyConstraint('silver_incident_id'),
    sa.UniqueConstraint('incident_code')
    )
    op.create_table('silver_sensor_reading',
    sa.Column('sensor_reading_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ingestion_batch_id', sa.UUID(), nullable=True),
    sa.Column('machine_id', sa.String(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sensor_type', sa.String(), nullable=True),
    sa.Column('sensor_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('is_missing', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_outlier', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['ingestion_batch_id'], ['ingestion_batch.ingestion_batch_id'], ),
    sa.PrimaryKeyConstraint('sensor_reading_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('silver_sensor_reading')
    op.drop_table('silver_incident')
    # ### end Alembic commands ###
