"""create_bronze_tables

Revision ID: b74e16597ef9
Revises: 
Create Date: 2026-06-22 16:17:56.773549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b74e16597ef9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bronze_incidents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('operator_name', sa.String(), nullable=True),
    sa.Column('machine_id', sa.String(), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('operator_badge', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('shift', sa.String(), nullable=True),
    sa.Column('type_surchauffe', sa.Integer(), nullable=True),
    sa.Column('type_baisse_pression', sa.Integer(), nullable=True),
    sa.Column('type_vibration', sa.Integer(), nullable=True),
    sa.Column('type_bruit_mecanique', sa.Integer(), nullable=True),
    sa.Column('type_surconsommation', sa.Integer(), nullable=True),
    sa.Column('type_blocage_mecanique', sa.Integer(), nullable=True),
    sa.Column('type_alarme_capteur', sa.Integer(), nullable=True),
    sa.Column('type_arret_urgence', sa.Integer(), nullable=True),
    sa.Column('type_defaut_qualite', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bronze_telemetry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('machine_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('pressure_bar', sa.Float(), nullable=True),
    sa.Column('voltage_mean_v', sa.Float(), nullable=True),
    sa.Column('rotation_mean_rpm', sa.Float(), nullable=True),
    sa.Column('pieces_produced', sa.Integer(), nullable=True),
    sa.Column('parse_ok', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('parse_ok_reason', sa.String(), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bronze_telemetry')
    op.drop_table('bronze_incidents')
    # ### end Alembic commands ###
