"""add_incidents_parse_flags

Revision ID: c2bcc04232cd
Revises: b74e16597ef9
Create Date: 2026-06-22 16:36:40.685892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2bcc04232cd'
down_revision: Union[str, Sequence[str], None] = 'b74e16597ef9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bronze_incidents', sa.Column('parse_ok', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('bronze_incidents', sa.Column('parse_ok_reason', sa.String(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bronze_incidents', 'parse_ok_reason')
    op.drop_column('bronze_incidents', 'parse_ok')
    # ### end Alembic commands ###
