"""add_ingestion_batch_operator_dq

Revision ID: cc83a31393a7
Revises: c2bcc04232cd
Create Date: 2026-06-22 19:06:12.696809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc83a31393a7'
down_revision: Union[str, Sequence[str], None] = 'c2bcc04232cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_batch',
    sa.Column('ingestion_batch_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_name', sa.String(), nullable=True),
    sa.Column('source_file', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rows_read', sa.Integer(), nullable=True),
    sa.Column('rows_loaded', sa.Integer(), nullable=True),
    sa.Column('rows_rejected', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ingestion_batch_id')
    )
    op.create_table('operator',
    sa.Column('operator_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operator_key', sa.String(), nullable=True),
    sa.Column('badge_hash', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('operator_id'),
    sa.UniqueConstraint('operator_key')
    )
    op.create_table('data_quality_issue',
    sa.Column('dq_issue_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ingestion_batch_id', sa.UUID(), nullable=True),
    sa.Column('dataset_name', sa.String(), nullable=True),
    sa.Column('rule_code', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('entity_key', sa.String(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_batch_id'], ['ingestion_batch.ingestion_batch_id'], ),
    sa.PrimaryKeyConstraint('dq_issue_id')
    )
    op.add_column('bronze_incidents', sa.Column('ingestion_batch_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'bronze_incidents', 'ingestion_batch', ['ingestion_batch_id'], ['ingestion_batch_id'])
    op.add_column('bronze_telemetry', sa.Column('ingestion_batch_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'bronze_telemetry', 'ingestion_batch', ['ingestion_batch_id'], ['ingestion_batch_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bronze_telemetry', type_='foreignkey')
    op.drop_column('bronze_telemetry', 'ingestion_batch_id')
    op.drop_constraint(None, 'bronze_incidents', type_='foreignkey')
    op.drop_column('bronze_incidents', 'ingestion_batch_id')
    op.drop_table('data_quality_issue')
    op.drop_table('operator')
    op.drop_table('ingestion_batch')
    # ### end Alembic commands ###
