"""add_gold_table

Revision ID: f9cde5e0c2a3
Revises: 454eda74d1b4
Create Date: 2026-06-23 11:55:10.539584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9cde5e0c2a3'
down_revision: Union[str, Sequence[str], None] = '454eda74d1b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gold_machine_hourly_feature',
    sa.Column('feature_row_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ingestion_batch_id', sa.UUID(), nullable=True),
    sa.Column('machine_id', sa.String(), nullable=True),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('temp_mean_24h', sa.Float(), nullable=True),
    sa.Column('temp_max_24h', sa.Float(), nullable=True),
    sa.Column('temp_std_24h', sa.Float(), nullable=True),
    sa.Column('pressure_mean_24h', sa.Float(), nullable=True),
    sa.Column('pressure_std_24h', sa.Float(), nullable=True),
    sa.Column('incident_count_prev_24h', sa.Integer(), nullable=True),
    sa.Column('incident_max_severity_prev_24h', sa.Integer(), nullable=True),
    sa.Column('label_failure_next_24h', sa.Boolean(), nullable=True),
    sa.Column('split_set', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ingestion_batch_id'], ['ingestion_batch.ingestion_batch_id'], ),
    sa.PrimaryKeyConstraint('feature_row_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gold_machine_hourly_feature')
    # ### end Alembic commands ###
